#!/bin/sh /etc/rc.common
# OpenClash 智能监控 init.d 脚本
# 适配 procd

START=99
STOP=10
USE_PROCD=1

start_service() {
    procd_open_instance
    procd_set_param command /usr/bin/openclash_smart_monitor.sh
    procd_set_param respawn
    procd_close_instance
}

stop_service() {
    killall openclash_smart_monitor.sh 2>/dev/null
}
